import type React from "react";
import {
  SiCmake,
  SiCplusplus,
  SiDocker,
  SiExpress,
  SiFastapi,
  SiGithubactions,
  SiJenkins,
  SiJest,
  SiLaravel,
  SiLeaflet,
  SiNestjs,
  SiNextdotjs,
  SiNginx,
  SiOpengl,
  SiPhp,
  SiPostgresql,
  SiReact,
  SiSocketdotio,
  SiSqlalchemy,
  SiSupabase,
  SiThreedotjs,
  SiTypescript,
  SiVite,
  SiVuedotjs,
} from "react-icons/si";

export const TECH_ICON: Record<string, React.ReactNode> = {
  "Next.js": <SiNextdotjs />,
  React: <SiReact />,
  Express: <SiExpress />,
  TypeScript: <SiTypescript />,
  Supabase: <SiSupabase />,
  Docker: <SiDocker />,
  Jenkins: <SiJenkins />,
  Jest: <SiJest />,
  "Vue 3": <SiVuedotjs />,
  Vite: <SiVite />,
  FastAPI: <SiFastapi />,
  SQLAlchemy: <SiSqlalchemy />,
  "GitHub Actions": <SiGithubactions />,
  Nginx: <SiNginx />,
  Leaflet: <SiLeaflet />,
  Laravel: <SiLaravel />,
  PHP: <SiPhp />,
  PostgreSQL: <SiPostgresql />,
  NestJS: <SiNestjs />,
  "Socket.io": <SiSocketdotio />,
  "C++": <SiCplusplus />,
  OpenGL: <SiOpengl />,
  CMake: <SiCmake />,
  "Three.js": <SiThreedotjs />,
};
